import { NextResponse } from 'next/server';
import { resolveDiscoveryManifest } from '@/lib/hermes/discovery/discovery-router';
import { LLMsRenderer } from '@/lib/hermes/discovery/renderers/llms-renderer';

export const dynamic = 'force-dynamic';

/**
 * 🤖 Standard LLMs.txt Discovery Endpoint
 * Format specification: https://llmstxt.org
 * Provides concise, structured context about Pandora's Growth OS & Hermes OS for AI models and scrapers.
 */
export async function GET() {
  try {
    // Try resolving default platform manifest (pandoras or snarai)
    const { manifest, tenantContext } = await resolveDiscoveryManifest('pandoras').catch(async () => {
      return await resolveDiscoveryManifest('snarai');
    });

    const renderer = new LLMsRenderer();
    const output = renderer.render(manifest, tenantContext);

    return new NextResponse(output, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'public, max-age=3600, stale-while-revalidate=86400',
      },
    });
  } catch (_err) {
    // Fallback static high-density canonical manifest for Pandora's Growth OS
    const fallbackText = `# Pandora's Growth OS & Hermes Intelligence

> Sovereign institutional tokenization and autonomous AI operating system powering Web3 protocols and real-world assets.

## Core Capabilities
- **Hermes OS**: Governed conversational intelligence with cryptographic claim contracts (RFC4648 CIDv1 on IPFS) and sovereign epistemic lattice.
- **Nexus Terminal**: Collaborative command center for platform administrators, operators, and ecosystem partners.
- **Sovereign Sign**: Notarized cryptographic deal rooms and investor onboarding pipelines.
- **Agora Tokenization**: Fractional capital participation, phase dynamics, and automated investor registry.
- **Agenda Soberana**: Sovereign operator scheduling, availability locks, and calendar management.

## Official Endpoints
- Dashboard: https://dash.pandoras.finance
- Nexus Terminal: https://nexus.pandoras.finance
- Admin Governance: https://admin.pandoras.finance
- Documentation: https://pandoras.finance/docs

---
Generated by Hermes Discovery Compiler v1.0.0`;

    return new NextResponse(fallbackText, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'public, max-age=3600, stale-while-revalidate=86400',
      },
    });
  }
}
