export const ACHIEVEMENTS = [
    // 1. First Steps & Activation
    {
        code: 'TG_FIRST_LOGIN',
        name: "Primer Login",
        description: "Conecta tu wallet exitosamente",
        icon: "🔗",
        type: "community_builder" as any,
        requiredPoints: 10,
        requiredLevel: 1,
        requiredEvents: ["DAILY_LOGIN"],
        pointsReward: 10,
        badgeUrl: "/badges/first-login.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_EXPLORER_25',
        name: "Explorador Intrépido",
        description: "Gana tus primeros 25 tokens",
        icon: "🔍",
        type: "first_steps" as any,
        requiredPoints: 25,
        requiredLevel: 1,
        requiredEvents: [],
        pointsReward: 25,
        badgeUrl: "/badges/explorer.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_ONBOARDING_COMPLETE',
        name: "Iniciado en Pandoras",
        description: "Has completado el recorrido de iniciación de Pandora's OS",
        icon: "🚀",
        type: "first_steps" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["onboarding_tour_completed"],
        pointsReward: 50,
        badgeUrl: "/badges/onboarding-complete.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },

    // 2. Creators / Applicants
    {
        code: 'TG_DRAFT_1',
        name: "Primer Borrador",
        description: "Envía tu primera aplicación de proyecto",
        icon: "📝",
        type: "creator" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["project_application_submitted"],
        pointsReward: 50,
        badgeUrl: "/badges/applicant.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_PROACTIVE_APPLICANT',
        name: "Aplicante Proactivo",
        description: "Gana 100 tokens por actividades",
        icon: "📝",
        type: "creator" as any,
        requiredPoints: 100,
        requiredLevel: 1,
        requiredEvents: ["project_application_started"],
        pointsReward: 100,
        badgeUrl: "/badges/applicant.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_PROJECT_APPROVED',
        name: "Proyecto Aprobado",
        description: "Tu proyecto fue aprobado por el equipo de Pandora's",
        icon: "✅",
        type: "creator" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["project_application_approved"],
        pointsReward: 100,
        badgeUrl: "/badges/project-approved.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_PROTOCOL_DEPLOYED',
        name: "Protocolo Desplegado",
        description: "Has desplegado tu propio protocolo en blockchain",
        icon: "🚀",
        type: "creator" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["protocol_deployed"],
        pointsReward: 500,
        badgeUrl: "/badges/protocol-deployert.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },

    // 3. Community Builders
    {
        code: 'TG_FIRST_REFERRAL',
        name: "Promotor de Comunidad",
        description: "Obtén tu primer referido exitoso",
        icon: "🎯",
        type: "community_builder" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["referral_made"],
        pointsReward: 500,
        badgeUrl: "/badges/referrer.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_MASTER_RECRUITER',
        name: "Maestro Recrutador",
        description: "Ayuda a 5 personas a unirse",
        icon: "🎉",
        type: "community_builder" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["referral_made_5"],
        pointsReward: 1000,
        badgeUrl: "/badges/recruiter.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_REFERRAL_COMPLETED',
        name: "Referido Completado",
        description: "Completa tu referido realizando acciones importantes",
        icon: "🎯",
        type: "community_builder" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["referral_completed"],
        pointsReward: 100,
        badgeUrl: "/badges/referral-completed.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },

    // 4. Tokenization & Learning
    {
        code: 'TG_COURSE_STARTED',
        name: "Curso Iniciado",
        description: "Has comenzado tu viaje de aprendizaje",
        icon: "📚",
        type: "tokenization_expert" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["course_started"],
        pointsReward: 10,
        badgeUrl: "/badges/scholar-start.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_COURSE_COMPLETED',
        name: "Curso Completado",
        description: "Has completado un curso educativo",
        icon: "🎓",
        type: "tokenization_expert" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["course_completed"],
        pointsReward: 100,
        badgeUrl: "/badges/scholar-complete.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },

    // 5. Artifact Collectors
    {
        code: 'TG_COLLECTOR_1',
        name: "Coleccionista Novato",
        description: "Adquiere tu primer Artefacto",
        icon: "🏺",
        type: "artifact_collector" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["artifact_purchased"],
        pointsReward: 50,
        badgeUrl: "/badges/collector-1.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_COLLECTOR_3',
        name: "Coleccionista Entusiasta",
        description: "Posees 3 Artefactos de la comunidad",
        icon: "🏺",
        type: "artifact_collector" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["artifact_purchased_3"],
        pointsReward: 150,
        badgeUrl: "/badges/collector-3.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_COLLECTOR_5',
        name: "Coleccionista Experto",
        description: "Posees 5 Artefactos de la comunidad",
        icon: "🏺",
        type: "artifact_collector" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["artifact_purchased_5"],
        pointsReward: 300,
        badgeUrl: "/badges/collector-5.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_COLLECTOR_10',
        name: "Ballena de Artefactos",
        description: "Posees 10 o más Artefactos. ¡Eres una leyenda!",
        icon: "🐋",
        type: "artifact_collector" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["artifact_purchased_10"],
        pointsReward: 1000,
        badgeUrl: "/badges/collector-whale.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },

    // 6. DAO & DeFi
    {
        code: 'TG_DAO_PIONEER',
        name: "Pionero DAO",
        description: "Has activado el sistema de Gobernanza Descentralizada",
        icon: "🏛️",
        type: "dao_pioneer" as any,
        requiredPoints: 0,
        requiredLevel: 2,
        requiredEvents: ["dao_activated"],
        pointsReward: 500,
        badgeUrl: "/badges/dao-pioneer.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_DEFI_STARTER',
        name: "Iniciación DeFi",
        description: "Tu primer depósito en Staking",
        icon: "🥩",
        type: "investor" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["staking_deposit"],
        pointsReward: 100,
        badgeUrl: "/badges/defi-starter.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_GOVERNOR_VOTE',
        name: "Voz Activa",
        description: "Tu primera participación en una votación del DAO",
        icon: "🗳️",
        type: "dao_pioneer" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["proposal_vote"],
        pointsReward: 50,
        badgeUrl: "/badges/governor.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    },
    {
        code: 'TG_YIELD_HUNTER_1',
        name: "Cazador de Rendimiento",
        description: "Tu primer reclamo de recompensas",
        icon: "💰",
        type: "early_adopter" as any,
        requiredPoints: 0,
        requiredLevel: 1,
        requiredEvents: ["rewards_claimed"],
        pointsReward: 75,
        badgeUrl: "/badges/yield-hunter.png",
        isActive: true,
        isSecret: false,
        createdAt: new Date()
    }
];
