import { PackManifest } from '../../runtimes/pack-types';

/**
 * Referral Trust Concierge Pack — Source Manifest v2.0
 *
 * El primer Solution Pack del ecosistema Hermes OS.
 * 
 * Instala una SOLUCIÓN COMPLETA para convertir contactos cálidos (familia/amigos
 * de founders) en inversores mediante confianza delegada, educación gradual, y
 * atención de concierge. No es solo un Journey: incluye Knowledge, Discovery,
 * Conversation, Media y Analytics en un solo paquete instalable.
 *
 * Estructura del Pack (fuente única de verdad):
 * 
 *   packs/referral-trust/
 *   ├── index.ts                    ← Este archivo (Manifest)
 *   ├── knowledge/
 *   │   ├── founder-story.md
 *   │   ├── investment-thesis.md
 *   │   ├── faq.md
 *   │   ├── qualification.md
 *   │   ├── family-context.md
 *   │   └── objections/
 *   │       ├── family.md
 *   │       ├── risk.md
 *   │       └── blockchain.md
 *   └── journeys/
 *       ├── main.md
 *       └── vip.md
 */
export const ReferralTrustPack: PackManifest = {
  id: 'referral_trust_concierge',
  version: '2.0.0',
  type: 'solution_pack', // Full solution, not just a journey
  publisher: 'pandoras_core',
  description: 'Convierte contactos cálidos (familia/amigos) en inversores mediante confianza delegada. Incluye Knowledge, Discovery, Conversation, Media y Analytics.',

  // Runtime Dependencies
  capabilities: [
    { runtime: 'conversation', version: '^1.0.0' },
    { runtime: 'memory', version: '^1.0.0' },
    { runtime: 'identity', version: '^1.0.0' },
    { runtime: 'discovery', version: '^1.0.0' },
  ],
  dependencies: [],

  // ── Knowledge (Declarative — each file is a first-class indexed asset) ──
  knowledge: [
    { id: 'founder_story',      source: 'knowledge/founder-story.md',       category: 'narrative',    priority: 'high', embeddable: true,  discoverable: true },
    { id: 'investment_thesis',  source: 'knowledge/investment-thesis.md',    category: 'thesis',       priority: 'high', embeddable: true,  discoverable: true },
    { id: 'faq',                source: 'knowledge/faq.md',                  category: 'support',      priority: 'high', embeddable: true,  discoverable: true },
    { id: 'qualification',      source: 'knowledge/qualification.md',        category: 'process',      priority: 'medium', embeddable: true, discoverable: false },
    { id: 'family_context',     source: 'knowledge/family-context.md',       category: 'context',      priority: 'medium', embeddable: true, discoverable: false },
    { id: 'objections_family',  source: 'knowledge/objections/family.md',    category: 'objection_handling', priority: 'high', embeddable: true, discoverable: false },
  ],

  // ── Journeys (declared as files, loaded by Compiler) ──
  journeys: [
    { id: 'main', source: 'journeys/main.md', isDefault: true },
  ],

  // ── Discovery Outputs (auto-generated by the Discovery Runtime) ──
  discovery: {
    entities: ['S\'Narai', 'Real Estate Tokenization', 'RWA', 'Blockchain Real Estate', 'Investment Token'],
    topics: ['tokenized real estate investment', 'family wealth building', 'alternative investments Mexico', 'RWA crypto'],
    schemas: ['Product', 'FAQPage', 'Organization'],
    generateLanding: true,
    generateLLMsTxt: true,
    generateSitemap: true,
  },

  // ── Conversation Config ──
  conversation: {
    defaultPersona: 'institutional_concierge',
    tone: 'warm, honest, knowledgeable but not pushy',
    language: 'es',
    responseStyle: 'conversational_short',
  },

  // ── Media Requests (each stage can request media assets from Media Co) ──
  media: {
    requests: [
      { stage: 'stage_02_value_prop', type: 'infographic', topic: 'investment_thesis' },
      { stage: 'stage_04_conversion', type: 'cta_image', topic: 'vip_access' },
    ],
  },

  // ── Outputs (what the Compiler will generate for this pack) ──
  outputs: {
    conversation: true,
    seo: true,
    media: true,
    widget: true,
    llms: true,
    analytics: true,
  },

  // ── Event Definitions ──
  events: {
    emits: [
      'referral.session_started',
      'referral.stage_advanced',
      'referral.objection_raised',
      'referral.objection_resolved',
      'referral.conversion_triggered',
      'referral.vip_access_requested',
    ],
  },

  permissions: ['read:knowledge', 'write:conversation_session', 'write:hermes_events', 'read:media'],
};
