import { CompiledDiscoveryManifest, IDiscoveryRenderer } from '../../runtimes/discovery-types';

/**
 * LLMs Renderer
 * Consumes a CompiledDiscoveryManifest and produces a llms.txt string.
 * 
 * Format based on llmstxt.org standard.
 * Hermes is invisible — the output looks like a native tenant file.
 */
export class LLMsRenderer implements IDiscoveryRenderer<string> {
  render(manifest: CompiledDiscoveryManifest, tenantContext: Record<string, any>): string {
    const { graph, faqs, pages } = manifest;
    const projectName = tenantContext.projectName || 'Project';
    const website = tenantContext.website || '';
    const description = tenantContext.description || '';

    const lines: string[] = [
      `# ${projectName}`,
      ``,
      `> ${description}`,
      ``,
      `## Overview`,
      ``,
      ...graph.entities.map(e => `- **${e.name}**: ${e.aliases.length > 0 ? e.aliases.join(', ') : e.schemaType}`),
      ``,
      `## Topics`,
      ``,
      ...graph.topics.map(t => `- ${t.label} (intent: ${t.searchIntent})`),
      ``,
    ];

    if (faqs.length > 0) {
      lines.push(`## FAQ`);
      lines.push(``);
      for (const faq of faqs) {
        lines.push(`### ${faq.question}`);
        lines.push(faq.answer);
        lines.push(``);
      }
    }

    if (pages.length > 0) {
      lines.push(`## Pages`);
      lines.push(``);
      for (const page of pages) {
        lines.push(`- [${page.title}](${website}${page.path}): ${page.description}`);
      }
      lines.push(``);
    }

    lines.push(`---`);
    lines.push(`Generated by Hermes Discovery Compiler v1.0.0`);

    return lines.join('\n');
  }
}
