#!/bin/bash

echo "🔧 CORRECCIÓN RÁPIDA DE GAMIFICACIÓN"
echo "=================================="
echo ""
echo "📋 INSTRUCCIONES:"
echo ""
echo "1. Ejecuta este SQL en tu base de datos PostgreSQL:"
echo ""
echo "ALTER TABLE \"gamification_events\" ALTER COLUMN \"user_id\" SET DATA TYPE integer;"
echo "ALTER TABLE \"gamification_profiles\" ALTER COLUMN \"user_id\" SET DATA TYPE integer;"
echo "ALTER TABLE \"user_achievements\" ALTER COLUMN \"user_id\" SET DATA TYPE integer;"
echo "ALTER TABLE \"user_points\" ALTER COLUMN \"user_id\" SET DATA TYPE integer;"
echo "ALTER TABLE \"user_rewards\" ALTER COLUMN \"user_id\" SET DATA TYPE integer;"
echo ""
echo "ALTER TABLE \"projects\" ALTER COLUMN \"status\" SET DEFAULT 'draft';"
echo ""
echo "2. Después de ejecutar el SQL, ejecuta:"
echo "   cd apps/dashboard && bun run dev"
echo ""
echo "3. Visita: http://localhost:3000/gamification-demo"
echo ""
echo "✅ ¡Tu sistema de gamificación estará funcionando!"