/**
 * 🏛️ HERMES AI REVENUE ENGINE — Module Index
 * Five-Engine Horizontal Architecture (v1.0)
 *
 * Phase 1 — Core Intelligence:
 *   KnowledgePackLoader, SalesStateMachineEngine, HermesDecisionEngine
 * Phase 2 — Communications Layer:
 *   Telegram InlineKeyboard (in webhook route)
 * Phase 3 — Commerce Engine:
 *   HermesCommerceEngine
 * Phase 4 — Intelligence Layer:
 *   HermesIntelligenceEngine
 * Phase 5 — B2B Marketplace (Agency Vault):
 *   /app/agency/vault/page.tsx
 */

export { KnowledgePackLoader, SNARAI_KNOWLEDGE_PACK } from './knowledge-pack';
export { SalesStateMachineEngine } from './state-machine';
export { HermesDecisionEngine } from './decision-engine';
export { HermesCommerceEngine } from './commerce-engine';
export { HermesIntelligenceEngine } from './intelligence-engine';
export type {
  SalesState,
  CustomerMemory,
  KnowledgePack,
  HermesMission,
} from './types';
export type { CommerceCheckoutSession } from './commerce-engine';
export type { AnonymousBehaviorEvent } from './intelligence-engine';

// Auto-generated exports
export * from './runtime/security-audit-logger';
export * from './intelligence/rwa/rwa-intelligence-provider';
export * from './revenue-closer/commercial-closer-service';
export * from './identity/interlocutor-resolver';
export * from './runtime/hermes-runtime';
export * from './interaction-router';
export * from './human-handoff';
export * from './soul/snarai-soul';
export * from './identity/identity-signer';
export * from './tenants/tenant-provisioner';
export * from './packs/real-estate-pack';
export * from './packs/real-estate-doctrine';
export * from './a2a/a2a-message-handler';
export * from './a2a/a2a-outbound-dispatcher';
export * from './a2a/a2a-security-validator';
export * from './a2a/agent-registry';
export * from './a2a/capability-grant-service';
export * from './a2a/contracts';
export * from './activity/service';
export * from './addons/catalog';
export * from './addons/context-merger';
export * from './addons/contracts/addon-capability';
export * from './addons/contracts/addon-compatibility';
export * from './addons/contracts/addon-governance';
export * from './addons/contracts/addon-installation';
export * from './addons/contracts/addon-manifest';
export * from './addons/governance';
export * from './addons/installation-manager';
export * from './addons/registry';
export * from './admin/platform-audit-ledger.service';
export * from './agents/HermesOutboundDispatcher';
export * from './agents/HermesWhatsAppOrchestrator';
export * from './alerts';
export * from './auth/canonical-resolver';
export * from './auth/hermes-session.types';
export * from './auth/rate-limiter';
export * from './auth/session-token.service';
export * from './auth/telegram-auth-validator';
export * from './auth/tenant-membership.service';
export * from './auth/wallet-tenant-membership';
export * from './auth/workspace-resolver';
export * from './bot/channel-gateway-adapter';
export * from './bot/identity-resolver';
export * from './bot/system-status';
export * from './builder/HermesBuilder';
export * from './capabilities/capability-runtime';
export * from './capabilities/types';
export * from './capability-dispatcher';
export * from './channel-gateway';
export * from './channels/adapter-registry';
export * from './channels/adapters/portal-adapter';
export * from './channels/adapters/telegram-adapter';
export * from './channels/adapters/whatsapp-adapter';
export * from './channels/binding-resolver';
export * from './channels/channel-adapter';
export * from './channels/channel-binding-types';
export * from './channels/channel-dispatcher';
export * from './channels/channel-errors';
export * from './channels/channel-mesh';
export * from './channels/channel-types';
export * from './channels/channel-vault.service';
export * from './channels/distribution/distribution-orchestrator.service';
export * from './channels/distribution/distribution-state-machine';
export * from './channels/distribution/sofia-execution-client';
export * from './channels/idempotency-store';
export * from './channels/normalized-message';
export * from './channels/omnichannel-gateway';
export * from './channels/outbound-router';
export * from './channels/publishers/direct-channel-publisher';
export * from './channels/publishers/newsletter-publisher';
export * from './channels/publishers/publisher.types';
export * from './channels/publishers/telegram-publisher';
export * from './channels/publishers/x-publisher';
export * from './channels/secret-resolver';
export * from './channels/tenant-channel.service';
export * from './commerce-engine';
export * from './compute/runpod-serverless.service';
export * from './compute/tenant-billing.service';
export * from './compute/tenant-credit-ledger.service';
export * from './context/surface-definition';
export * from './contracts/attribution';
export * from './contracts/capability-contracts';
export * from './contracts/governance-contracts';
export * from './contracts/handoff';
export * from './contracts/identity-contracts';
export * from './contracts/mission-contracts';
export * from './contracts/nurture';
export * from './contracts/opportunity';
export * from './contracts/pack-contracts';
export * from './contracts/qualification';
export * from './contracts';
export type { ConversationContext, ChannelContext, ExecutionContext } from './contracts';
export * from './control-plane/application/commands/approve-intent';
export * from './control-plane/application/commands/knowledge/create-knowledge-source';
export * from './control-plane/application/commands/knowledge/update-knowledge-source';
export * from './control-plane/application/commands/reject-intent';
export * from './control-plane/application/context';
export * from './control-plane/application/queries/get-active-missions';
export * from './control-plane/application/queries/get-knowledge-overview';
export * from './control-plane/application/queries/get-mission-audit-trail';
export * from './control-plane/application/queries/get-organization-overview';
export * from './control-plane/application/queries/get-pending-intents';
export * from './conversation-manager';
export * from './crm/crm-models';
export * from './crm/sales-workflow';
export * from './data-provider';
export * from './decision-engine';
export * from './demand/demand-distribution.service';
export * from './demand/demand-intent-handler';
export * from './discovery/discovery-router';
export * from './discovery/renderers/llms-renderer';
export * from './discovery/renderers/schema-renderer';
export * from './discovery/renderers/sitemap-renderer';
export * from './domains/campaign/campaign-repository';
export * from './domains/campaign/campaign';
export * from './engines/commercial/marketing.facade';
export * from './engines/commercial/marketing.provider';
export * from './engines/content/ai/ai-adapter-layer';
export * from './engines/content/assets/asset-engine';
export * from './engines/content/media-engine.provider';
export * from './engines/content/research/research-engine';
export * from './event-bus';
export * from './events/contracts';
export * from './events/event-spine';
export * from './events/handlers/analytics-handler';
export * from './events/handlers/planner-handler';
export * from './events/handlers/snapshot-handler';
export * from './events/mission-event-bus';
export * from './execution/adapters/adapter-contracts';
export * from './execution/adapters/native-adapter';
export * from './execution/capabilities/create-referral-campaign';
export * from './execution/capabilities/crm-update-stage';
export * from './execution/capabilities/send-telegram-notification';
export * from './execution/checkpoint-repository';
export * from './execution/contracts/capability-contracts';
export * from './execution/contracts/execution-state';
export * from './execution/default-execution-journal';
export * from './execution/default-execution-runtime';
export * from './execution/default-policy-engine';
export * from './execution/event-replayer';
export * from './execution/execution-director';
export * from './execution/execution-instance';
export * from './execution/execution-journal';
export * from './execution/execution-os';
export * from './execution/execution-runtime';
export * from './execution/execution-snapshot';
export * from './execution/feedback-loop';
export * from './execution/human-interaction-service';
export * from './execution/outbox-handlers';
export * from './execution/persistent-execution-runtime';
export * from './execution/policy-engine';
export * from './execution/ports/repositories/governance-event-repository.interface';
export * from './execution/ports/repositories/operational-intent-repository.interface';
export * from './execution/ports/repositories/strategy-decision-repository.interface';
export * from './execution/ports/telegram-credentials';
export * from './execution/ports/transactions/approval-transaction.interface';
export * from './execution/workflow-definition';
export * from './execution/workflow-registry';
export * from './execution/workflow-state-machine';

export * from './executive/audit-service';
export * from './executive/briefing-engine';
export * from './executive/capabilities-manifest';
export * from './executive/code-operator';
export * from './executive/executive-planner';
export * from './executive/financial-orchestrator';
export * from './executive/founder-directives';
export * from './executive/intent-classifier';
export * from './executive/invariants';
export * from './executive/types';
export * from './goal-recognizer';
export * from './governance/approval-service';
export * from './governance/events/contracts';
export * from './governance/events/governance-event-bus';
export * from './governance/intent-manager';
export * from './governance/policy-evaluator';
export * from './hermes-shell';
export * from './human-handoff';
export * from './identity/assembler';
export * from './identity/canonical-identity-graph';
export * from './identity/contact-doctrine';
export * from './identity/contracts';
export * from './identity/identity-signer';
export * from './identity/identity-verifier';
export * from './identity/interlocutor-resolver';
export * from './identity/resolvers';
export * from './identity/tenant-context-resolver';
export * from './intelligence/geo/contracts';
export * from './intelligence/geo/geo-citability-engine';
export * from './intelligence/research/autonomous-research-engine';
export * from './intelligence/research/contracts';
export * from './intelligence/rwa/rwa-intelligence-provider';
export * from './intelligence/seo/contracts';
export * from './intelligence/seo/seo-audit-engine';
export * from './intelligence/seo/seo-competitor-engine';
export * from './intelligence/seo/seo-content-engine';
export * from './intelligence/seo/seo-schema-engine';
export * from './intelligence-engine';
export * from './intent-engine';
export * from './interaction-router';
export * from './journeys/domain';
export * from './journeys/errors';
export * from './journeys/repositories';
export * from './journeys/transition-validator';
export * from './kernel/boot/boot-sequence';
export * from './kernel/execution/dispatcher';

export * from './kernel/execution/resource-manager';
export * from './kernel/intelligence/decision-journal';
export * from './kernel/scheduler/scheduler';
export * from './kernel/transport/http-transport';
export * from './kernel/transport/transport-layer';
export * from './knowledge/acquisition';
export * from './knowledge/asset-repository';
export * from './knowledge/claim-contract-engine';
export * from './knowledge/context-factory';
export * from './knowledge/ecosystem-doctrine';
export * from './knowledge/envelope-vault';
export * from './knowledge/exclusion-register';
export * from './knowledge/growth-intelligence';
export * from './knowledge/growth-read-adapter';
export * from './knowledge/ipfs/canonical-cid';
export * from './knowledge/ipfs/contracts';
export * from './knowledge/ipfs/ipfs-alerting';
export * from './knowledge/ipfs/kubo-provider';
export * from './knowledge/ipfs/mock-provider';
export * from './knowledge/ipfs/orchestrator';
export * from './knowledge/ipfs/pinata-provider';
export * from './knowledge/ipfs/storage-policy';
export * from './knowledge/ipfs/storage-repair';
export * from './knowledge/ipfs-vault';
export * from './knowledge/knowledge-asset';
export * from './knowledge/knowledge-engine';
export * from './knowledge/knowledge-runtime';
export * from './knowledge/knowledge-types';
export * from './knowledge/nexus-intelligence';
export * from './knowledge/nexus-read-adapter';
export * from './knowledge/pattern-extractor';
export * from './knowledge/portal-intelligence';
export * from './knowledge/portal-read-adapter';
export * from './knowledge/registry-manifest';
export * from './knowledge/registry';
export * from './knowledge/service';
export * from './knowledge/vault-authorization-gate';
export * from './knowledge-pack';
export * from './marketplace/marketplace-api';
export * from './mcp/contracts';
export * from './mcp/mcp-bridge';
export * from './media/hermes-media-orchestrator.service';
export * from './memory/canonical-memory-service';
export * from './memory/learning-loop';
export * from './memory/types';
export * from './memory-layers';
export * from './mission-manager';
export * from './mission-planner';
export * from './nexus/agents-service';
export * from './nexus/attention-item';
export * from './nexus/collaborators-service';
export * from './nexus/nexus-authorization';
export * from './onboarding/onboarding-intelligence';
export * from './onboarding/orchestrator';
export * from './onboarding/policies';
export * from './onboarding/proposal-engine';
export * from './onboarding/types';
export * from './onboarding/validator';
export * from './onboarding-workflow';
export * from './overview/service';
export * from './packs/domain-pack-loader';
export * from './packs/hermes-internal-domain-pack';
export * from './packs/real-estate-doctrine';
export * from './packs/real-estate-pack';
export * from './packs/snarai-domain-pack';
export * from './payments/adapters/base-adapter';
export * from './payments/adapters/growth-adapter';
export * from './payments/adapters/rwa-adapter';

export * from './payments/core/orchestrator';
export * from './payments/core/types';
export * from './planner';
export * from './platform/calendar/calendar-service';
export * from './platform/events/default-event-bus';
export * from './platform/events/event-bus';
export * from './platform/events/event-subscriber';
export * from './policies/policy-engine';
export * from './proactive/proactive-cooldown';
export * from './proactive/proactive-dispatcher';
export * from './proactive/proactive-policy';
export * from './proactive/signal-detector';
export * from './proactive/signal-registry';
export * from './providers/abstract-provider';
export * from './providers/cognitive-provider';
export * from './providers/compatibility-provider';
export * from './providers/external-provider';
export * from './providers/ollama-provider';
export * from './providers/openai-provider';
export * from './providers/provider-factory';
export * from './providers/test-stub-provider';
export * from './qa/cli';
export * from './qa/matchers/deterministic-matchers';
export * from './qa/matchers/policy-matchers';
export * from './qa/matchers/semantic-matchers';
export * from './qa/runner/certification-policy';
export * from './qa/runner/qa-runner';
export * from './qa/scenarios/follow-up-scenarios';
export * from './qa/scenarios/full-funnel-scenarios';
export * from './qa/scenarios/governance-scenarios';
export * from './qa/scenarios/interactive-scenarios';
export * from './qa/scenarios/memory-scenarios';
export * from './qa/scenarios/objection-scenarios';
export * from './qa/scenarios/security-scenarios';
export * from './qa/types';
export * from './receipts/receipt-explorer';
export * from './reconciliation/hermes-reconciliation-sweeper.service';
export * from './registries/binding-registry';
export * from './registries/provider-registry';
export * from './registries/service-registry';
export * from './registry/dependencies';
export * from './registry/pack-registry';
export * from './revenue-closer/commercial-closer-service';
export * from './revenue-closer/executive-handoff-service';
export * from './revenue-closer/nurture-engine';
export * from './revenue-closer/revenue-closer-engine';
export * from './runtime/cognitive-response-parser';
export * from './runtime/cognitive-runtime-listener';
export * from './runtime/context-adapter';
export * from './runtime/context-hygiene-validator';
export * from './runtime/conversation-context-builder';
export * from './runtime/egress-guard';
export * from './runtime/hermes-runtime';
export * from './runtime/identity/actor-identity-resolver';
export * from './runtime/journey-engine';
export * from './runtime/llm-provider';
export * from './runtime/memory/contracts';
export * from './runtime/memory/memory-adapter';
export * from './runtime/memory/postgres-memory-provider';
export * from './runtime/memory-engine';
export * from './runtime/operational-governance-contract';
export * from './runtime/policy/snarai-response-policy-gate';
export * from './runtime/policy-validator';
export * from './runtime/prompt-builder';
export * from './runtime/prompt-compiler';
export * from './runtime/prompt-hygiene-contract';
export * from './runtime/reasoning-providers';
export * from './runtime/sandbox/code-sandbox';
export * from './runtime/sandbox/integrity-guard';
export * from './runtime/sandbox/memory-scrubber';
export * from './runtime/scope-validator';
export * from './runtime/security-audit-logger';
export * from './runtime/skill-resolver';
export * from './runtime/strategy-governance-bridge';
export * from './runtime/tenant-session-token';
export * from './runtime/tool-authorization-gate';
export * from './runtime/tool-executor';
export * from './runtime/tools/executive-tool-registry';
export * from './runtime/tools/executive-tools';
export * from './runtime/trace/trace-recorder';
export * from './runtime/universal-security-gates';
export * from './runtimes/action-runtime';
export * from './runtimes/artifact-store';
export * from './runtimes/base';
export * from './runtimes/content-compiler';
export * from './runtimes/content-types';
export * from './runtimes/conversation-runtime';
export * from './runtimes/decision-provider';
export * from './runtimes/discovery-compiler';
export * from './runtimes/discovery-types';
export * from './runtimes/entry-runtime';
export * from './runtimes/evidence-provider';
export * from './runtimes/execution-scheduler';
export * from './runtimes/executors';
export * from './runtimes/hermes-kernel';
export * from './runtimes/intent-runtime';
export * from './runtimes/json-binding-repository';
export * from './runtimes/media-runtime';
export * from './runtimes/module-loader';
export * from './runtimes/navigation-provider';
export * from './runtimes/ollama-provider';
export * from './runtimes/pack-compiler';
export * from './runtimes/pack-installer';
export * from './runtimes/prospect-identity-resolver';
export * from './runtimes/prospect-intelligence-runtime';
export * from './runtimes/prospect-intelligence-service';
export * from './runtimes/prospect-intelligence-types';
export * from './runtimes/prospect-strategy-service';
export * from './runtimes/runtime-compiler';
export * from './runtimes/security-provider';
export * from './runtimes/session-manager';
export * from './runtimes/ui-runtime';
export * from './sdk/create-app';
export * from './sdk/create-runtime';
export * from './sdk/define-adapter';
export * from './sdk/define-capability';
export * from './sdk/define-workflow';
export * from './simulator-types';
export * from './skill-registry';
export * from './skills/catalog';
export * from './skills/contracts';
export * from './skills/registry';
export * from './soul/snarai-soul';
export * from './state-machine';
export * from './strategy.service';
export * from './telegram-runtime/keyboards';
export * from './telegram-runtime/live-phases';
export * from './telegram-runtime/messages';
export * from './telegram-runtime/router';
export * from './telegram-runtime/state';
export * from './tenants/contracts';
export * from './tenants/governance-service';
export * from './tenants/tenant-authority';
export * from './tenants/tenant-gateway';
export * from './tenants/tenant-provisioner';
export * from './tool-registry';
export * from './tools/browser/browser-provider';
export * from './tools/browser/contracts';
export * from './tools/web/contracts';
export * from './tools/web/web-crawl-tool';
export * from './tools/web/web-extract-tool';
export * from './tools/web/web-fetch-tool';
export * from './tools/web/web-search-provider';
export * from './trial/hermes-experience-provisioner.service';
export * from './trial/hermes-trial-policy.service';
export * from './trial/hermes-trial-timeline.service';
export * from './types';
export * from './workflow-engine';
export * from './workflow-resolver';export { TenantContextResolver } from './identity/tenant-context-resolver';
export { NexusAuthorizationService } from './nexus/nexus-authorization';

export * from './nexus/legacy/telegram-team-transport';
export * from './nexus/legacy/nexus-action-dispatcher';

export * from './nexus/legacy/notifications/TelegramDispatcher';
export * from './identity/index';
export { EscalationService } from './escalation/escalation-service';
export { HermesNotificationDispatcher } from './notifications/notification-dispatcher';
export type { RuntimeMessage, RuntimeStreamEvent, ToolAuthorizationRequest, KnowledgeClassificationTier, ReasoningContext } from './runtime/contracts';
export { HermesCognitiveLayer } from './hermes-cognitive';
export type { KnowledgeDimension, GovernedKnowledgeItem, KnowledgeVisibility, KnowledgeMutationEvent } from './knowledge/types';
export type { EscalationReason, EscalationStatus } from './escalation/escalation-service';
export { setExecutionOSPort, setDiscordWebhookPort, setMarketingDomainPort, setProjectDomainPort } from './ports';
export * from './execution/outbox-handlers';
export * from './execution/execution-os';
export { CapabilityRegistry as ExecutionCapabilityRegistry } from './execution/capability-registry';
export * from './execution/feedback-loop';
export * from './execution/capabilities/create-referral-campaign';
export * from './execution/capabilities/send-telegram-notification';
export * from './execution/capabilities/crm-update-stage';
export { NexusActionDispatcher } from './nexus/legacy/nexus-action-dispatcher';
export { NexusTeamTransport } from './nexus/legacy/telegram-team-transport';
export type { NexusResourceScope } from './nexus/nexus-authorization';
export * from './admin/platform-audit-ledger.service';
export { ShadowVerificationEngine } from './knowledge/shadow-verifier';
export * from './payments/PaymentCoreService';
export * from './provisioning/ProvisioningEngine';
